import { storage } from "./storage";

const sampleProperties = [
  {
    idImovel: "1234567890001",
    tipoVenda: "AUCTION",
    titulo: "RESIDENCIAL PARK GARDEN",
    descricao: "3 Quartos, 1 Suíte, 2 Vagas na Garagem, Sala, Cozinha, Área de Serviço, WC.",
    tipoImovel: "Apartamento",
    quartos: 3,
    garagem: 2,
    areaTotal: 89.5,
    areaPrivativa: 72.3,
    areaTerreno: null,
    endereco: "RUA DAS PALMEIRAS, N. 456 APTO. 302, JARDIM EUROPA - CEP: 04549-000, SAO PAULO - SP",
    bairro: "JARDIM EUROPA",
    cidade: "SAO PAULO",
    uf: "SP",
    cep: "04549-000",
    valorAvaliacao: 680000,
    valorMinVenda: 408000,
    valorMinVenda1Leilao: 680000,
    valorMinVenda2Leilao: 408000,
    desconto: 40,
    aceitaFGTS: 1,
    aceitaFinanciamento: 0,
    urlImagem: null,
    fotos: null,
    linkEdital: "https://venda-imoveis.caixa.gov.br/editais/EL00800225CPARE.PDF",
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890001",
    edital: "0080/0226 - CPA/RE",
    leiloeiro: "LEILOEIRO OFICIAL SP",
    dataLeilao1: "15/04/2026 10h00",
    dataLeilao2: "22/04/2026 10h00",
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 9500,
    precoAluguelM2: 45,
    scoreFLIP: 82,
    scoreReforma: 75,
    scoreAluguel: 60,
    scoreGeral: 78,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890002",
    tipoVenda: "DIRECT",
    titulo: "CONDOMÍNIO VILA VERDE",
    descricao: "2 Quartos, 1 Vaga na Garagem, Sala, Cozinha, Área de Serviço.",
    tipoImovel: "Casa",
    quartos: 2,
    garagem: 1,
    areaTotal: 120,
    areaPrivativa: 85,
    areaTerreno: 200,
    endereco: "RUA ANTONIO CARLOS, N. 1234, CENTRO - CEP: 30130-000, BELO HORIZONTE - MG",
    bairro: "CENTRO",
    cidade: "BELO HORIZONTE",
    uf: "MG",
    cep: "30130-000",
    valorAvaliacao: 320000,
    valorMinVenda: 192000,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 40,
    aceitaFGTS: 1,
    aceitaFinanciamento: 1,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890002",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "partial",
    tributos: "buyer",
    precoM2Mercado: 5200,
    precoAluguelM2: 28,
    scoreFLIP: 88,
    scoreReforma: 90,
    scoreAluguel: 72,
    scoreGeral: 85,
    favorito: 1,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890003",
    tipoVenda: "ONLINE",
    titulo: "EDIFÍCIO SOL NASCENTE",
    descricao: "1 Quarto, 1 Vaga na Garagem, Sala, Cozinha.",
    tipoImovel: "Apartamento",
    quartos: 1,
    garagem: 1,
    areaTotal: 45.8,
    areaPrivativa: 38.2,
    areaTerreno: null,
    endereco: "AV BRASIL, N. 789 APTO. 1205, COPACABANA - CEP: 22041-080, RIO DE JANEIRO - RJ",
    bairro: "COPACABANA",
    cidade: "RIO DE JANEIRO",
    uf: "RJ",
    cep: "22041-080",
    valorAvaliacao: 520000,
    valorMinVenda: 338000,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 35,
    aceitaFGTS: 0,
    aceitaFinanciamento: 0,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890003",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 14000,
    precoAluguelM2: 65,
    scoreFLIP: 70,
    scoreReforma: 55,
    scoreAluguel: 85,
    scoreGeral: 72,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890004",
    tipoVenda: "AUCTION",
    titulo: "RESIDENCIAL FLORES DO CAMPO",
    descricao: "2 Quartos, 1 Vaga na Garagem, Sala, Cozinha, Área de Serviço.",
    tipoImovel: "Apartamento",
    quartos: 2,
    garagem: 1,
    areaTotal: 58.3,
    areaPrivativa: 48.7,
    areaTerreno: null,
    endereco: "RUA VOLUNTÁRIOS DA PÁTRIA, N. 234 APTO. 501, SANTANA - CEP: 02011-000, SAO PAULO - SP",
    bairro: "SANTANA",
    cidade: "SAO PAULO",
    uf: "SP",
    cep: "02011-000",
    valorAvaliacao: 380000,
    valorMinVenda: 190000,
    valorMinVenda1Leilao: 380000,
    valorMinVenda2Leilao: 190000,
    desconto: 50,
    aceitaFGTS: 1,
    aceitaFinanciamento: 1,
    urlImagem: null,
    fotos: null,
    linkEdital: "https://venda-imoveis.caixa.gov.br/editais/EL00800226CPARE.PDF",
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890004",
    edital: "0081/0226 - CPA/RE",
    leiloeiro: "LEILOEIRO OFICIAL SP",
    dataLeilao1: "18/04/2026 14h00",
    dataLeilao2: "25/04/2026 14h00",
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 8200,
    precoAluguelM2: 38,
    scoreFLIP: 92,
    scoreReforma: 85,
    scoreAluguel: 68,
    scoreGeral: 88,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890005",
    tipoVenda: "DIRECT",
    titulo: "CASA RESIDENCIAL JARDIM DAS ACÁCIAS",
    descricao: "3 Quartos, 1 Suíte, 2 Vagas na Garagem, Sala, Cozinha, Área de Serviço, Quintal.",
    tipoImovel: "Casa",
    quartos: 3,
    garagem: 2,
    areaTotal: 180,
    areaPrivativa: 130,
    areaTerreno: 300,
    endereco: "RUA DAS ACÁCIAS, N. 567, JARDIM DAS ACÁCIAS - CEP: 80540-000, CURITIBA - PR",
    bairro: "JARDIM DAS ACÁCIAS",
    cidade: "CURITIBA",
    uf: "PR",
    cep: "80540-000",
    valorAvaliacao: 450000,
    valorMinVenda: 270000,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 40,
    aceitaFGTS: 1,
    aceitaFinanciamento: 1,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890005",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "none",
    tributos: "buyer",
    precoM2Mercado: 6500,
    precoAluguelM2: 32,
    scoreFLIP: 75,
    scoreReforma: 82,
    scoreAluguel: 70,
    scoreGeral: 76,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890006",
    tipoVenda: "AUCTION",
    titulo: "EDIFÍCIO ATLÂNTICO",
    descricao: "2 Quartos, 1 Vaga na Garagem, Sala, Cozinha, WC.",
    tipoImovel: "Apartamento",
    quartos: 2,
    garagem: 1,
    areaTotal: 65.2,
    areaPrivativa: 55.8,
    areaTerreno: null,
    endereco: "RUA SETE DE SETEMBRO, N. 890 APTO. 704, BOA VIAGEM - CEP: 51020-030, RECIFE - PE",
    bairro: "BOA VIAGEM",
    cidade: "RECIFE",
    uf: "PE",
    cep: "51020-030",
    valorAvaliacao: 290000,
    valorMinVenda: 145000,
    valorMinVenda1Leilao: 290000,
    valorMinVenda2Leilao: 145000,
    desconto: 50,
    aceitaFGTS: 1,
    aceitaFinanciamento: 0,
    urlImagem: null,
    fotos: null,
    linkEdital: "https://venda-imoveis.caixa.gov.br/editais/EL00800227CPARE.PDF",
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890006",
    edital: "0082/0226 - CPA/RE",
    leiloeiro: "LEILOEIRO OFICIAL PE",
    dataLeilao1: "20/04/2026 10h00",
    dataLeilao2: "27/04/2026 10h00",
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 7000,
    precoAluguelM2: 35,
    scoreFLIP: 90,
    scoreReforma: 88,
    scoreAluguel: 78,
    scoreGeral: 87,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890007",
    tipoVenda: "BID",
    titulo: "GALPÃO COMERCIAL DISTRITO INDUSTRIAL",
    descricao: "Galpão comercial com escritório, banheiros e estacionamento.",
    tipoImovel: "Comercial",
    quartos: null,
    garagem: 5,
    areaTotal: 450,
    areaPrivativa: 420,
    areaTerreno: 800,
    endereco: "ROD BR-101, KM 234, DISTRITO INDUSTRIAL - CEP: 88160-000, BIGUACU - SC",
    bairro: "DISTRITO INDUSTRIAL",
    cidade: "BIGUACU",
    uf: "SC",
    cep: "88160-000",
    valorAvaliacao: 890000,
    valorMinVenda: 534000,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 40,
    aceitaFGTS: 0,
    aceitaFinanciamento: 0,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890007",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "none",
    tributos: "buyer",
    precoM2Mercado: 3200,
    precoAluguelM2: 18,
    scoreFLIP: 45,
    scoreReforma: 50,
    scoreAluguel: 55,
    scoreGeral: 50,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890008",
    tipoVenda: "ONLINE",
    titulo: "RESIDENCIAL MONTE CARLO",
    descricao: "3 Quartos, 1 Suíte, 2 Vagas na Garagem, Varanda, Sala, Cozinha.",
    tipoImovel: "Apartamento",
    quartos: 3,
    garagem: 2,
    areaTotal: 110,
    areaPrivativa: 92,
    areaTerreno: null,
    endereco: "AV JURACY MAGALHÃES, N. 2345 APTO. 1502, PITUBA - CEP: 41810-600, SALVADOR - BA",
    bairro: "PITUBA",
    cidade: "SALVADOR",
    uf: "BA",
    cep: "41810-600",
    valorAvaliacao: 550000,
    valorMinVenda: 302500,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 45,
    aceitaFGTS: 1,
    aceitaFinanciamento: 1,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890008",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 6800,
    precoAluguelM2: 33,
    scoreFLIP: 80,
    scoreReforma: 78,
    scoreAluguel: 65,
    scoreGeral: 76,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890009",
    tipoVenda: "DIRECT",
    titulo: "TERRENO RESIDENCIAL ALPHAVILLE",
    descricao: "Terreno residencial em condomínio fechado.",
    tipoImovel: "Terreno",
    quartos: null,
    garagem: null,
    areaTotal: 500,
    areaPrivativa: null,
    areaTerreno: 500,
    endereco: "RUA DOS MANACÁS, LOTE 45, ALPHAVILLE - CEP: 06454-000, BARUERI - SP",
    bairro: "ALPHAVILLE",
    cidade: "BARUERI",
    uf: "SP",
    cep: "06454-000",
    valorAvaliacao: 400000,
    valorMinVenda: 240000,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 40,
    aceitaFGTS: 0,
    aceitaFinanciamento: 0,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890009",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "none",
    tributos: "buyer",
    precoM2Mercado: 1200,
    precoAluguelM2: null,
    scoreFLIP: 65,
    scoreReforma: null,
    scoreAluguel: null,
    scoreGeral: 55,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890010",
    tipoVenda: "AUCTION",
    titulo: "APARTAMENTO RESIDENCIAL PARQUE DAS NAÇÕES",
    descricao: "2 Quartos, 1 Vaga na Garagem, Sala, Cozinha, Área de Serviço.",
    tipoImovel: "Apartamento",
    quartos: 2,
    garagem: 1,
    areaTotal: 52.4,
    areaPrivativa: 44.1,
    areaTerreno: null,
    endereco: "RUA GOIÁS, N. 678 APTO. 201, AGUA VERDE - CEP: 80620-060, CURITIBA - PR",
    bairro: "AGUA VERDE",
    cidade: "CURITIBA",
    uf: "PR",
    cep: "80620-060",
    valorAvaliacao: 310000,
    valorMinVenda: 170500,
    valorMinVenda1Leilao: 310000,
    valorMinVenda2Leilao: 170500,
    desconto: 45,
    aceitaFGTS: 1,
    aceitaFinanciamento: 1,
    urlImagem: null,
    fotos: null,
    linkEdital: "https://venda-imoveis.caixa.gov.br/editais/EL00800228CPARE.PDF",
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890010",
    edital: "0083/0226 - CPA/RE",
    leiloeiro: "LEILOEIRO OFICIAL PR",
    dataLeilao1: "22/04/2026 14h00",
    dataLeilao2: "29/04/2026 14h00",
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 7800,
    precoAluguelM2: 36,
    scoreFLIP: 86,
    scoreReforma: 80,
    scoreAluguel: 72,
    scoreGeral: 82,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890011",
    tipoVenda: "DIRECT",
    titulo: "SOBRADO RESIDENCIAL VILA NOVA",
    descricao: "4 Quartos, 2 Suítes, 3 Vagas na Garagem, Sala, Cozinha, Churrasqueira.",
    tipoImovel: "Casa",
    quartos: 4,
    garagem: 3,
    areaTotal: 250,
    areaPrivativa: 200,
    areaTerreno: 350,
    endereco: "RUA CARLOS GOMES, N. 890, VILA NOVA - CEP: 13073-000, CAMPINAS - SP",
    bairro: "VILA NOVA",
    cidade: "CAMPINAS",
    uf: "SP",
    cep: "13073-000",
    valorAvaliacao: 750000,
    valorMinVenda: 412500,
    valorMinVenda1Leilao: null,
    valorMinVenda2Leilao: null,
    desconto: 45,
    aceitaFGTS: 1,
    aceitaFinanciamento: 1,
    urlImagem: null,
    fotos: null,
    linkEdital: null,
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890011",
    edital: null,
    leiloeiro: null,
    dataLeilao1: null,
    dataLeilao2: null,
    condominio: "none",
    tributos: "buyer",
    precoM2Mercado: 5500,
    precoAluguelM2: 25,
    scoreFLIP: 72,
    scoreReforma: 80,
    scoreAluguel: 58,
    scoreGeral: 70,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
  {
    idImovel: "1234567890012",
    tipoVenda: "AUCTION",
    titulo: "APARTAMENTO BEIRA MAR NORTE",
    descricao: "3 Quartos, 1 Suíte, 2 Vagas na Garagem, Varanda com Vista Mar, Sala, Cozinha.",
    tipoImovel: "Apartamento",
    quartos: 3,
    garagem: 2,
    areaTotal: 105,
    areaPrivativa: 88,
    areaTerreno: null,
    endereco: "AV BEIRA MAR NORTE, N. 1567 APTO. 1801, CENTRO - CEP: 88015-600, FLORIANOPOLIS - SC",
    bairro: "CENTRO",
    cidade: "FLORIANOPOLIS",
    uf: "SC",
    cep: "88015-600",
    valorAvaliacao: 920000,
    valorMinVenda: 552000,
    valorMinVenda1Leilao: 920000,
    valorMinVenda2Leilao: 552000,
    desconto: 40,
    aceitaFGTS: 0,
    aceitaFinanciamento: 0,
    urlImagem: null,
    fotos: null,
    linkEdital: "https://venda-imoveis.caixa.gov.br/editais/EL00800229CPARE.PDF",
    linkMatricula: null,
    linkImovel: "https://venda-imoveis.caixa.gov.br/sistema/detalhe-imovel.asp?hdnimovel=1234567890012",
    edital: "0084/0226 - CPA/RE",
    leiloeiro: "LEILOEIRO OFICIAL SC",
    dataLeilao1: "25/04/2026 10h00",
    dataLeilao2: "02/05/2026 10h00",
    condominio: "full",
    tributos: "buyer",
    precoM2Mercado: 11000,
    precoAluguelM2: 50,
    scoreFLIP: 78,
    scoreReforma: 70,
    scoreAluguel: 82,
    scoreGeral: 77,
    favorito: 0,
    notas: null,
    dataColeta: "2026-03-28",
  },
];

const sampleMarketData = [
  { cidade: "SAO PAULO", uf: "SP", bairro: "JARDIM EUROPA", tipoImovel: "Apartamento", precoM2Venda: 9500, precoM2Aluguel: 45, precoM2AluguelCurta: 120, taxaOcupacao: 70, tendencia: "up" },
  { cidade: "SAO PAULO", uf: "SP", bairro: "SANTANA", tipoImovel: "Apartamento", precoM2Venda: 8200, precoM2Aluguel: 38, precoM2AluguelCurta: 95, taxaOcupacao: 65, tendencia: "stable" },
  { cidade: "BELO HORIZONTE", uf: "MG", bairro: "CENTRO", tipoImovel: "Casa", precoM2Venda: 5200, precoM2Aluguel: 28, precoM2AluguelCurta: 70, taxaOcupacao: 60, tendencia: "up" },
  { cidade: "RIO DE JANEIRO", uf: "RJ", bairro: "COPACABANA", tipoImovel: "Apartamento", precoM2Venda: 14000, precoM2Aluguel: 65, precoM2AluguelCurta: 180, taxaOcupacao: 75, tendencia: "stable" },
  { cidade: "CURITIBA", uf: "PR", bairro: "JARDIM DAS ACÁCIAS", tipoImovel: "Casa", precoM2Venda: 6500, precoM2Aluguel: 32, precoM2AluguelCurta: 80, taxaOcupacao: 55, tendencia: "up" },
  { cidade: "CURITIBA", uf: "PR", bairro: "AGUA VERDE", tipoImovel: "Apartamento", precoM2Venda: 7800, precoM2Aluguel: 36, precoM2AluguelCurta: 90, taxaOcupacao: 65, tendencia: "up" },
  { cidade: "RECIFE", uf: "PE", bairro: "BOA VIAGEM", tipoImovel: "Apartamento", precoM2Venda: 7000, precoM2Aluguel: 35, precoM2AluguelCurta: 100, taxaOcupacao: 70, tendencia: "stable" },
  { cidade: "SALVADOR", uf: "BA", bairro: "PITUBA", tipoImovel: "Apartamento", precoM2Venda: 6800, precoM2Aluguel: 33, precoM2AluguelCurta: 90, taxaOcupacao: 60, tendencia: "stable" },
  { cidade: "BARUERI", uf: "SP", bairro: "ALPHAVILLE", tipoImovel: "Terreno", precoM2Venda: 1200, precoM2Aluguel: null, precoM2AluguelCurta: null, taxaOcupacao: null, tendencia: "up" },
  { cidade: "CAMPINAS", uf: "SP", bairro: "VILA NOVA", tipoImovel: "Casa", precoM2Venda: 5500, precoM2Aluguel: 25, precoM2AluguelCurta: 65, taxaOcupacao: 55, tendencia: "stable" },
  { cidade: "FLORIANOPOLIS", uf: "SC", bairro: "CENTRO", tipoImovel: "Apartamento", precoM2Venda: 11000, precoM2Aluguel: 50, precoM2AluguelCurta: 150, taxaOcupacao: 72, tendencia: "up" },
  { cidade: "BIGUACU", uf: "SC", bairro: "DISTRITO INDUSTRIAL", tipoImovel: "Comercial", precoM2Venda: 3200, precoM2Aluguel: 18, precoM2AluguelCurta: null, taxaOcupacao: null, tendencia: "stable" },
];

export function seedDatabase() {
  // Check if already seeded
  const existing = storage.getProperties();
  if (existing.total > 0) {
    console.log(`Database already has ${existing.total} properties, skipping seed.`);
    return;
  }

  console.log("Seeding database with sample data...");

  for (const prop of sampleProperties) {
    storage.createProperty(prop as any);
  }

  for (const market of sampleMarketData) {
    storage.createMarketData(market as any);
  }

  console.log(`Seeded ${sampleProperties.length} properties and ${sampleMarketData.length} market data entries.`);
}
